[workspace]
members = ["day01", "day02", "day03", "day04", "day06", "day07", "day25", "io"]

[profile.dev]
lto = true
panic = "abort"
opt-level = 1

[profile.release]
opt-level = 3
lto = true
panic = "abort"
