[workspace]
members = ["day01", "day02", "day04", "io"]

[profile.dev]
lto = true
opt-level = 3
debug-assertions = false
overflow-checks = false
panic = "abort"

[profile.release]
opt-level = 3
lto = true
panic = "abort"
