[package]
name = "day19"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0"
regex = "1.5"
glam = "0.20"
lazy_static = "1.4"

[workspace]