name: run
on:
  push:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: mrkits/rust-mos
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: rustup toolchain link mos /usr/local/rust-mos
      - run: rustup default mos
      - run: cargo run -p day01
