name: run
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      cargo_options:
        description: 'cargo options'
        required: false
        default: ''
jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: mrkits/rust-mos
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: rustup toolchain link mos /usr/local/rust-mos
      - run: rustup default mos
      - run: env

      # cargo run 2>&1 | grep "available binaries: " | cut -b 21- | sed 's/, / /g' | xargs -n 1 | grep -v 'day09\|day10\|day12\|day16\|day24' | xargs -n 1 cargo run -p
      - run: cargo run -p day01 ${{ github.event.inputs.cargo_opts }}
      - run: cargo run -p day02 ${{ github.event.inputs.cargo_opts }}
      - run: cargo run -p day03 ${{ github.event.inputs.cargo_opts }}
      - run: cargo run -p day04 ${{ github.event.inputs.cargo_opts }}
      - run: cargo run -p day05 ${{ github.event.inputs.cargo_opts }}
      - run: cargo run -p day06 ${{ github.event.inputs.cargo_opts }}
      - run: cargo run -p day07 ${{ github.event.inputs.cargo_opts }}  # slow
      - run: cargo run -p day08 ${{ github.event.inputs.cargo_opts }}
      - run: cargo run -p day09 ${{ github.event.inputs.cargo_opts }}
      - run: cargo run -p day10 ${{ github.event.inputs.cargo_opts }}
      - run: cargo run -p day11 ${{ github.event.inputs.cargo_opts }}
      - run: cargo run -p day12 ${{ github.event.inputs.cargo_opts }}  # slow
      - run: cargo run -p day13 ${{ github.event.inputs.cargo_opts }}
      - run: cargo run -p day14 ${{ github.event.inputs.cargo_opts }}
      - run: cargo run -p day16 ${{ github.event.inputs.cargo_opts }}
      - run: cargo run -p day17 ${{ github.event.inputs.cargo_opts }}
      - run: cargo run -p day18 ${{ github.event.inputs.cargo_opts }}
      # - run: cargo run -p day24  # sloooow
      - run: cargo run -p day25 ${{ github.event.inputs.cargo_opts }}  # slow
