name: run
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      cargo_opts:
        description: 'cargo options'
        required: false
        default: ''
jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: mrkits/rust-mos
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: rustup toolchain link mos /usr/local/rust-mos
      - run: rustup default mos
      - run: env
      - run: echo CARGO_RUN="cargo run ${{ github.event.inputs.cargo_opts }}" >> $GITHUB_ENV
      - run: ${{ env.CARGO_RUN }} -p day01
      - run: ${{ env.CARGO_RUN }} -p day02
      - run: ${{ env.CARGO_RUN }} -p day03
      - run: ${{ env.CARGO_RUN }} -p day04
      # - run: ${{ env.CARGO_RUN }} -p day05 # fails after 20221231
      - run: ${{ env.CARGO_RUN }} -p day06
      - run: ${{ env.CARGO_RUN }} -p day07   # slow
      - run: ${{ env.CARGO_RUN }} -p day08
      - run: ${{ env.CARGO_RUN }} -p day09
      - run: ${{ env.CARGO_RUN }} -p day10
      - run: ${{ env.CARGO_RUN }} -p day11
      - run: ${{ env.CARGO_RUN }} -p day12   # slow
      - run: ${{ env.CARGO_RUN }} -p day13
      - run: ${{ env.CARGO_RUN }} -p day14
      - run: ${{ env.CARGO_RUN }} -p day16
      - run: ${{ env.CARGO_RUN }} -p day17
      - run: ${{ env.CARGO_RUN }} -p day18
      # - run: ${{ env.CARGO_RUN }} -p day24  # sloooow
      - run: ${{ env.CARGO_RUN }} -p day25   # slow
